qa_dict = {
    "id": "",
    "target": "",
    "tool": "",
    "type": [],
    "category": [],
    "frequency": [],
    "notes": "",
    "comments": "",
    "references": [],
    "coverage": {
        "rock": "",
        "initial_weathering": "",
        "field": "",
        "watershed": "",
        "ocean": "",
        "lca": "",
        "impacts": "",
    },
    "EW001": {"relationship": "", "citation": "", "comments": ""},
    "EW002": {"relationship": "", "citation": "", "comments": ""},
}


protocols_dict = {
    "id": "",
    "entity": "",
    "protocol": "",
    "metadata": {
        "links": "",
        "year": "",
        "status": "",
        "notes": "",
        "comments": "",
    },
    "timeline": {
        "application": "",
        "weathering": "",
        "registration": "",
        "measurement": "",
        "verification": "",
        "crediting": "",
    },
    "practices": {
        "geographies": "",
        "application_site": "",
        "feedstock": "",
        "notes": "",
        "comments": "",
    },
    "rigor": {
        "score": "",
        "details": {
            "regime": "",
            "rock_characterization": "",
            "initial_weathering": "",
            "field": "",
            "watershed": "",
            "ocean": "",
            "time_dynamics": "",
            "empirical_redundancy": "",
            "sampling_approach": "",
            "model_validation": "",
            "uncerta" "y": "",
            "lca": "",
            "notes": "",
            "comments": "",
        },
    },
    "additionality": {
        "score": "",
        "details": {
            "baseline": "",
            "counterfactual_carbonate_weathering": "",
            "tests": "",
            "notes": "",
            "comments": "",
        },
    },
    "safeguards": {
        "score": "",
        "details": {
            "application": "",
            "toxic_elements": "",
            "soil_physical_properties": "",
            "yield": "",
            "notes": "",
            "comments": "",
        },
    },
    "governance": {
        "score": "",
        "details": {
            "credit_timing": "",
            "data_transparency": "",
            "model_transparency": "",
            "learning_and_updates": "",
            "notes": "",
            "comments": "",
        },
    },
    "rating": "",
    "revisions": {"date": "", "note": ""},
}
