name: ew
channels:
  - conda-forge
dependencies:
  - fsspec
  - gspread
  - jupyter
  - numpy
  - oauth2client
  - pandas
  - pandera
  - pip
  - pre-commit
  - python=3.10
  - regex
  - s3fs
  - ujson
  - xarray
